[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
crowdfi = "BVdntsDPm3vs11M1H4Vvt6DxAZpvE1KDca89D7LrDRxe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
